version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make build
      - run: make test
  deploy:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # A little tricky to cache inmges between jobs, so just rebuild.
      - run: make build
      - run: make deploy

workflows:
  version: 2
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
